//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LordG.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LordG.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HA
        ///Net
        ///Bag
        ///SSAO
        ///None
        ///cATM
        ///mDeco
        ///cPost
        ///Npc02
        ///XLink
        ///Slope
        ///mWall
        ///squ13
        ///cTalk
        ///ant00
        ///Npc01
        ///Npc00
        ///Mouth
        ///SSSSS
        ///Npc03
        ///cat00
        ///mFloor
        ///mMusic
        ///ImmQ_3
        ///Coffee
        ///Camera
        ///Office
        ///ImmQ_2
        ///mParams
        ///cNormal
        ///WorldAo
        ///Invalid
        ///mCommon
        ///Airport
        ///cDefault
        ///Bridge04
        ///Museum02
        ///MiniGame
        ///Tailor01
        ///NpcColor
        ///Tailor00
        ///Player00
        ///Player01
        ///Market01
        ///Museum00
        ///Market02
        ///Museum01
        ///FtrActor
        ///Bridge05
        ///Bridge03
        ///Market00
        ///EnvParam
        ///NetConfig
        ///TreeParam
        ///MainField
        ///AreaParam
        ///mFanParam
        ///cFishBait
        ///cItemMenu
        ///CapsuleA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ACNHBYML {
            get {
                return ResourceManager.GetString("ACNHBYML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16x9
        ///1stDamage
        ///2DWater
        ///2D_PAUSE_IGNORE
        ///2PGuidance
        ///2PGuidance%03d
        ///2PGuidanceIcon
        ///2PGuidanceTitle%03d
        ///2Way
        ///2bytes/flag
        ///2ndDamage
        ///::ACTOR_TRANS
        ///::BASE_MATRIX
        ///::FIX_POSITION
        ///::OTHER_MATRIX
        ///::OTHER_TRANS
        ///&lt;Anonymous&gt;
        ///AButtonPosC
        ///AButtonPosD
        ///AButtonPosU
        ///AButtonPosition
        ///AFTER_IMAGE_EFFECT
        ///AFTER_INDIRECT
        ///AP
        ///ATR1
        ///AbekobeGalaxy
        ///AbsorbCoin
        ///AccelRateToBckPos
        ///Accell
        ///Access
        ///Action
        ///ActionBgmCtrl
        ///ActionFlagCtrl
        ///ActionFootPrintCtrl
        ///ActionName
        ///ActionScreenBlurCtrl
        ///ActionSe
        ///ActionType
        ///Acti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FieldNames {
            get {
                return ResourceManager.GetString("FieldNames", resourceCulture);
            }
        }
    }
}
