name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/Lord-Giganticus/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}  
    - name: Build
      run: dotnet publish --configuration Release
    - name: Publish
      run: dotnet nuget push "LordG.IO/bin/Release/LordG.IO.1.1.2.nupkg" --skip-duplicate
